### ISSUE TITLE
Download model weights baidu 

### ISSUE THREAD

**Issue by makemate** [zhang-tao-whu/DVIS_Plus#1]
Thanks for sharing your repo with the public. 
My issue is not related to the code but to downloading the weights from the [Model zoo](https://github.com/zhang-tao-whu/DVIS_Plus/blob/main/MODEL_ZOO.md).
I was able to download the ResNet50 weights (Mask2Former(instance) | R50 | COCO | OVIS,YTVIS19&21 | where a direct link was provided without issues: https://dl.fbaipublicfiles.com/maskformer/mask2former/coco/instance/maskformer2_R50_bs16_50ep/model_final_3c8ec9.pkl . 
Now I wanted to download the weights of the VIT-L model but I was not able to start the download. Not knowing any Chinese I just have always downloaded the BaiduNetDisk installer. Is there an option to download the weights directly without creating a baidu user account or downloading the app?

**Comment by zhang-tao-whu** [comment]
Thanks for your attention. I will provide a download link for OneDrive or Google Drive. Please wait for a few days.

**Comment by zhang-tao-whu** [comment]
Hi, I have uploaded all the weights to Hugging Face. You can download them from [here](https://huggingface.co/zhangtao-whu/DVIS_Plus/tree/main/DVIS%2B%2B).

**Comment by makemate** [comment]
Great service, thank you!
