### ISSUE TITLE
Temporal Refiner in Online Mode

### ISSUE THREAD

**Issue by egeozsoy** [zhang-tao-whu/DVIS_Plus#12]
First of all, congrats on a really great work.

 I had a question about the temporal refiner in the online setting: Would it not be possible to still use a temporal refiner for processing the current frame, so that this segmentation is improved by the past frames? It seems like you are not using any temporal refinement in the online processing setting.

Many thanks in advance

**Comment by zhang-tao-whu** [comment]
Yes, the Temporal Refiner can be used in online mode with just some slight modifications. Simply remove the convolution in the Temporal Refiner and run self-attention on the temporal dimension in casual mode. Significant gains can still be achieved. These explorations will be reported in this repository and the paper. However, this may take some time. If needed, you can try exploring it yourself.

**Comment by egeozsoy** [comment]
Thank you for the quick response!
