### ISSUE TITLE
VIPSeg Panoptic Segmentation Eval Error

### ISSUE THREAD

**Issue by egeozsoy** [zhang-tao-whu/DVIS_Plus#13]
I am trying to run VIPSeg evaluation as you have suggested:

```
python train_net_video.py
--num-gpus 1
--config-file configs/dvis_Plus/VIPSeg/CTVIS_r50.yaml
--eval-only MODEL.WEIGHTS DVIS_Plus/mask2former/ctvis_r50_vipseg.pth 
```

But I am getting the following error:

  ```
File "/home/guests/ege_oezsoy/MultiModalOperatingRoom/DVIS_Plus/train_net_video.py", line 260, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/guests/ege_oezsoy/miniconda3/envs/MultiModalOperatingRoom/lib/python3.10/site-packages/detectron2/evaluation/evaluator.py", line 164, in inference_on_dataset
    evaluator.process(inputs, outputs)
  File "/home/guests/ege_oezsoy/MultiModalOperatingRoom/DVIS_Plus/dvis_Plus/data_video/vps_eval.py", line 108, in process
    segments_infos = outputs['segments_infos']
KeyError: 'segments_infos'
```

Upon further inspection, it seems to me that some part of the code/model is not properly processing the output as a panoptic segmentation, because the output has the following keys: ['image_size', 'pred_scores', 'pred_labels' , 'pred_masks']

I wanted to ask you if you have encountered a similar issue, and if you have any suggestions on how to infer/eval in panoptic segmentation mode with the VIPSeg dataset. Maybe I am configuring something wrong?

Thank you for you help

**Comment by zhang-tao-whu** [comment]
Everything is normal. You have finished fine-tuning the Segmenter, and you can now use this weight for subsequent online and offline DVIS training. Currently, CTVIS and MinVIS only support VIS inference. They are only used to provide pre-trained Segmenter for DVIS. Evaluation of VSS and VPS can only be conducted when running DVIS online or offline.
