### ISSUE TITLE
demo.py: error: unrecognized arguments:   --merge: command not found

### ISSUE THREAD

**Issue by erictan23** [zhang-tao-whu/DVIS_Plus#2]
Hi! I am new to open vocab VIS and I am currently testing it out. I encountered some problems as I am running the visualisation mode of the code. It caught an error of unrecognised argument, --merge seems to be the problem in this case. I am unsure of what to do so that I get to try this model. 
I am trying to segment/detect person and cash using open vocab models. Do let me know on what I am doing wrong and what I should adjust...
![image](https://github.com/zhang-tao-whu/DVIS_Plus/assets/74151994/98e01444-5a4d-4830-aa86-48fc63d0030a)

**Comment by erictan23** [comment]
I have also tried other pre-trained models, but it seems like the same consistent issue occur, --merge and --opt are not recognised.
![image](https://github.com/zhang-tao-whu/DVIS_Plus/assets/74151994/d073705b-0d6e-4b4b-82ce-4103be7acef4)

**Comment by erictan23** [comment]
Issue was on the commandline closing \, there were some spaces when copying the command.

**Comment by Sillyyk** [comment]
> Issue was on the commandline closing , there were some spaces when copying the command.

Have you solved the problem? My testing instructions are basically the same as yours. May I ask if you have encountered this situation: RuntimeError: The shape of the 2D attnmask is torch Size([77, 77]), but should be (128, 128).
