### ISSUE TITLE
eval: KeyError: 'video_id` / demo: AttributeError: 'list' object has no attribute 'to'

### ISSUE THREAD

**Issue by j-ys** [zhang-tao-whu/DVIS_Plus#3]
Hello,  Thank you for all materials :)
I successfully trained my custom dataset(the original format is COCO, and already used coco2ytvis tools) using the DVIS_Plus model, and I made my config file(.yaml).

I had 2 Errors,
1) **When I run evaluation code,** 
`!python train_net_video.py --num-gpus 1 --config-file /home/user/dvis2/DVIS_Plus/output_CTVIS_R50_YTVIS21_custom_0205/cfg2.yaml --eval-only MODEL.WEIGHTS /home/user/dvis2/DVIS_Plus/output_CTVIS_R50_YTVIS21_custom_0205/model_final.pth`

`File "/home/user/dvis2/DVIS_Plus/dvis_Plus/data_video/datasets/ytvis_api/ytvos.py", line 81, in createIndex
    vidToAnns[ann['video_id']].append(ann)
**KeyError: 'video_id`**
But, my annotation files already exist 'video_id`.

2) **When I run demo,**
`!python demo_video/demo_long_video.py --config-file /home/user/dvis2/DVIS_Plus/output_CTVIS_R50_YTVIS21_custom_0205/config.yaml --input /home/user/dvis2/DVIS_Plus/datasets/train_exd/merged_scenario --output /home/user/dvis2/DVIS_Plus/datasets/train_exd/visualization --opts MODEL.WEIGHTS /home/user/dvis2/DVIS_Plus/output_CTVIS_R50_YTVIS21_custom_0205/model_final.pth`

` File "demo_video/demo_long_video.py", line 124, in <module>
    predictions, visualized_output = demo.run_on_video(vid_frames, keep=False)
  File "/home/user/dvis2/DVIS_Plus/demo_video/predictor.py", line 161, in run_on_video
    predictions = self.predictor((frames, keep))
...
  File "/home/user/anaconda3/envs/dvis2/lib/python3.8/site-packages/torch/jit/_trace.py", line 1112, in wrapper
    return fn(*args, **kwargs)
  File "/home/user/anaconda3/envs/dvis2/lib/python3.8/site-packages/detectron2/layers/wrappers.py", line 170, in move_device_like
    return src.to(dst.device)
**AttributeError: 'list' object has no attribute 'to'**`
But, in 'def move_device_like(src: torch.Tensor, dst: torch.Tensor)' src is already Tensor type.

**Comment by zhang-tao-whu** [comment]
(1) Currently video AP evaluation is not supported on image datasets. (2) the MinVis or CTVis models (segmenter + matching algorithm) only support generating demos using demo.py. Only DVIS online or offline can utilize demo_long_video.py.

**Comment by j-ys** [comment]
Thank you for your quick response! Then, How can I evlaluate my dataset and config? I want to train/eval/inference COCO dataset to video

**Comment by j-ys** [comment]
And also when I use demo.py, AttributeError: 'list' object has no attribute 'to' again..

**Comment by j-ys** [comment]
I solved problems to use detectron2's demo/demo.py! Thank you
