### ISSUE TITLE
infer

### ISSUE THREAD

**Issue by txy00001** [zhang-tao-whu/DVIS_Plus#6]
demo：
--thing_classes  carrot,carrots lantern,lanterns \
--stuff_classes hay \
————————————
Hello, first of all, thank you very much for open-source such an algorithm library, it is a very good project, and secondly, I have a few questions I would like to ask: (1) When opening vocabulary video segmentation, my video may have a code scanner, coil and the like, is it possible to add my category directly in the demo "--thing_classes"? (2) If I want to detect and segment an open factory scene, and split some obvious artifacts, such as toolboxes, plastic films, etc., can I directly use the weight of your OV to reason directly?③Don't  support direct video input?If I want to reason on a new video? Do we need to divide the new video into frames every time? Can't we directly input the entire video and then customize the output of a certain number of frames of the video?

**Comment by zhang-tao-whu** [comment]
For (1), you can directly add the categories you want to segment in the '--thing_classes' parameter, and try to expand some synonyms to increase recall. For (2), I believe it's possible, although these categories may be rare in the training data. For (3), currently, there is no functionality to directly accept videos as input. You can implement a function to read the video frame by frame and replace the process of reading the image folder in demo.py.
