### ISSUE TITLE
error running

### ISSUE THREAD

**Issue by txy00001** [zhang-tao-whu/DVIS_Plus#7]
![image](https://github.com/zhang-tao-whu/DVIS_Plus/assets/47891269/41a0ebf4-5a0c-4f44-8ad4-340e189e4732)
There was an error running，this is my code 
![image](https://github.com/zhang-tao-whu/DVIS_Plus/assets/47891269/65df3e83-32f0-43f1-8ff8-dff71fbd3c5b)
I've downloaded the model，

**Comment by zhang-tao-whu** [comment]
Hello, this is because there is a need to obtain the CLIP model from Hugging Face, but you are unable to access Hugging Face. You can use a mirror instead, such as `export HF_ENDPOINT=https://hf-mirror.com/`.
