### ISSUE TITLE
Error while Evaluation

### ISSUE THREAD

**Issue by Shuaicong97** [zhang-tao-whu/DVIS_Plus#8]
Hi, first thank you for your work!

I want to reproduce the results of your paper in Table 1 (the best, i.e. DVIS++ with VIT-L and OVIS). So I downloaded the **offline_vitl_ovis_534.pth**.

**Comment by Shuaicong97** [comment]
> Hi, first thank you for your work!
> 
> I want to reproduce the results of your paper in Table 1 (the best, i.e. DVIS++ with VIT-L and OVIS). So I downloaded the **offline_vitl_ovis_534.pth**. Here's my command: `python train_net_video.py --num-gpus 4 --config-file configs/dvis_Plus/ovis/vit_adapter/DVIS_Plus_Offline_VitAdapterL.yaml --eval-only MODEL.WEIGHTS /path/to/offline_vitl_ovis_534.pth` And the places I modified in DVIS_Plus_Offline_VitAdapterL.yaml: <img alt="image" width="915" src="https://private-user-images.githubusercontent.com/56966410/318456722-31bdf29f-c3ec-4bba-bf47-5d85c96818ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTYyMjgsIm5iZiI6MTcxMTk5NTkyOCwicGF0aCI6Ii81Njk2NjQxMC8zMTg0NTY3MjItMzFiZGYyOWYtYzNlYy00YmJhLWJmNDctNWQ4NWM5NjgxOGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE4MjUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYmQ2NGQxZjc3ZGFmYjI3YWFhNGRlMDZhNzBjOTc5OWNiMmRiZWQ4NzcwYzRjYWU0OGEyZmI4MGY5NzExOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PqPCMR9P5E0PbOAdVNuJIpWgI-c_Z_w_svqDZjTF7-g"> and in train_net_video.py: <img alt="image" width="511" src="https://private-user-images.githubusercontent.com/56966410/318456299-2cfb122c-faec-4a05-a611-8891f5ea5668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTYyMjgsIm5iZiI6MTcxMTk5NTkyOCwicGF0aCI6Ii81Njk2NjQxMC8zMTg0NTYyOTktMmNmYjEyMmMtZmFlYy00YTA1LWE2MTEtODg5MWY1ZWE1NjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE4MjUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NGQxNTJjZTYxODQ2NTYxOTQ4YTE2NmM4MjZmMzVmZDMwYjcyZmI4YmJjNTc2ODMyYTM2MjA1MGFhN2I3YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FaCZiWtYsyGtY9yq2tcsJbb47dJ-a98MaZFppp6Wz2Y">
> 
> I have three questions:
> 
> 1. Am I using the correct weight file?
> 2. Should the path in the command **/path/to/weight.pth** and the path in the yaml file for **VIT_WEIGHT** be the same?
> 3. After running this command, I have such error:
>    interpolated_weight = F.interpolate(weight['patch_embed.proj.weight'],
>    KeyError: 'patch_embed.proj.weight'
> 
> <img alt="image" width="1068" src="https://private-user-images.githubusercontent.com/56966410/318458859-27e89cef-81e2-41cc-8951-7c16177e4165.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTYyMjgsIm5iZiI6MTcxMTk5NTkyOCwicGF0aCI6Ii81Njk2NjQxMC8zMTg0NTg4NTktMjdlODljZWYtODFlMi00MWNjLTg5NTEtN2MxNjE3N2U0MTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE4MjUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMDJlOTE1M2M3OTc2NDgzNTJmNjRmZTM2ZmQ3ZjY4OTFhODJhZjFhMTdjZDZmNGQ3NWU0MjU2OGNkMjI0ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.829ZtBLxdDuCxTxVewCdqs7CzGJEegbsWQJ8jmCN4uY"> But I checked, it's using the weight file.
> How to solve this issue? Thank you in advance!

Update: 
I found that the key name has changed. So I changed it to `interpolated_weight = F.interpolate(weight['model']['backbone.vit_module.patch_embed.proj.weight'],
                                        size=(16, 16), mode='bilinear',
                                        align_corners=True)
    weight['model']['backbone.vit_module.patch_embed.proj.weight'] = interpolated_weight
    model.load_state_dict(weight)`, and run. But new errors occur:
<img width="1418" alt="image" src="https://github.com/zhang-tao-whu/DVIS_Plus/assets/56966410/9526db1d-0e1b-45ab-97c8-d5aa9b05daae">
How to solve that?

**Comment by Sillyyk** [comment]
I would like to ask you how the effect is

**Comment by Sillyyk** [comment]
> Hi, first thank you for your work!
> 
> I want to reproduce the results of your paper in Table 1 (the best, i.e. DVIS++ with VIT-L and OVIS). So I downloaded the **offline_vitl_ovis_534.pth**.

I would like to ask you how the effect is
